ui:
  title: 1DSPP

spring:
  jmx:
    enabled: false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  datasource:
    url: jdbc:postgresql://localhost:5432/spp
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver